// stylings
import './scss/app.scss';

// scripts
// helpers
import './js/helpers/smooth-scroll';
// elements
import './js/elements/accordion';
import './js/elements/announcement';
import './js/elements/departments';
import './js/elements/fade-scroll';
import './js/elements/faq-sidebar';
import './js/elements/footer-copyright';
import './js/elements/navigation';
import './js/elements/search';
import './js/elements/stable-link';
import './js/elements/view-filters';
import './js/elements/view-header';
import './js/elements/tooltip';
import './js/elements/ordered-list';
